workflows:
  build_godbody:
    name: Build GODBODY for iOS
    max_build_duration: 60
    environment:
      vars:
        BUNDLE_ID: "com.angelinadavini.godbody"
        APP_NAME: "GODBODY"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync ios
    artifacts:
      - build/ios/**/*.ipa
